version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.22.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
      - "9901:9901"
    extra_hosts:
      - "host.docker.internal:host-gateway"